### ISSUE TITLE
Intermediate snapping points do not seem to be working on SlidingSheetDialog

### ISSUE THREAD

**Issue by SherpaMiguel** [flutterwtf/wtf_sliding_sheet#25]
When using more than 2 snapping points on SlidingSheetDialog, e.g [0.3, 0.7, 1], intermediate snapping is not working.

**Comment by kirznernasta** [comment]
Hi! Thank you for your message. Can you please provide more detailed information that makes you think that intermediate snapping is not working?

**Comment by kirznernasta** [comment]
When smoothly expanded and compressed, our widget can remain at any intermediate snap value, but in the case of a sudden scroll, as you can see in the attached GIF, the widget will expand to the values you specified (in this example, snappings are [0.3, 0.7, 1.0]).

![device-2023-07-05-155127](https://github.com/What-the-Flutter/wtf_sliding_sheet/assets/94079414/ae6a626d-1397-4008-b630-d36991137e5a)

However, the exception you've received seems to indicate that there may be issues with properly configuring our widget. Please recheck our [example](https://github.com/What-the-Flutter/wtf_sliding_sheet/tree/master/example) and ensure that your code is correct. Thank you for your watchfulness!
